image: maven:latest

stages:
  - sca
  - build

veracode_agent_sca:
  stage: sca
  script: 
    - git checkout master
    - curl -sSL https://download.sourceclear.com/ci.sh | sh

maven_build:
  stage: build
  script:
    - mvn clean package