image: maven:latest

stages:
  - git
  - sca
  - build

git_clone:
  stage: git
  script:
    git clone https://github.com/m-browntown/vera-java-example.git

veracode_agent_sca:
  stage: sca
  script: 
    curl -sSL https://download.sourceclear.com/ci.sh | sh


maven_build:
  stage: build
  script:
    - mvn clean package